export { HomePage } from "./HomePage";
export { SignInPage } from "./SignInPage";
export { SignUpPage } from "./SignUpPage";
export { ConsentPage } from "./ConsentPage";
export { MentalHealthResultsPage } from "./MentalHealthResultsPage";
export { DashboardPage } from "./DashboardPage";
export { ReportsPage } from "./ReportsPage";
export { AccountsPage } from "./AccountsPage";
export { ResourcesPage } from "./ResourcesPage";
export { HelpSupportPage } from "./HelpSupportPage";
export { HistoryPage } from "./HistoryPage";
export { InsightsPage } from "./InsightsPage";
export { AidFunctionPage } from "./AidFunctionPage";
export { StudentsPage } from "./StudentsPage";
export { MessagesPage } from "./MessagesPage";
export { default as AppointmentsPage } from "./AppointmentsPage";
